### ISSUE TITLE
Can't connect to any WebTorrent trackers In Chrome

### ISSUE THREAD

**Issue by 117503445** [subins2000/WebDrop#59]
![image](https://github.com/subins2000/WebDrop/assets/21152034/aa183035-a18c-42ad-847a-cd0893ed6f8a)

```
App.vue:221 Error: Connection error: Failed to construct 'RTCPeerConnection': 'stun:global.stun.twilio.com:3478?transport=udp' is not a valid stun or turn URL.
    at p.r (websocket-tracker.js:413:35)
    at Object.h (events.js:243:26)
    at u.emit (events.js:153:5)
    at p._destroy (index.js:461:19)
    at p.destroy (index.js:404:10)
    at index.js:107:33
```

Can't connect to tracer in chrome, but FireFox can.

I think the reason is that one of the dependencies is using the wrong STUN server `stun:global.stun.twilio.com:3478?transport=udp` but this is illegal.

You can refer to <https://github.com/twilio/twilio-video.js/issues/1934>

**Comment by subins2000** [comment]
Yikes so that's why it's not working on Chrome. I think updating `simple-peer` of `p2pt` dependency should fix this. Need some time to figure how to do this without breaking anything else. Hmmmm
